import img1 from "@/assets/markets/1.png";
import img10 from "@/assets/markets/10.png";
import img11 from "@/assets/markets/11.png";
import img12 from "@/assets/markets/12.png";
import img13 from "@/assets/markets/13.png";
import img14 from "@/assets/markets/14.png";
import img15 from "@/assets/markets/15.png";
import img16 from "@/assets/markets/16.png";
import img17 from "@/assets/markets/17.png";
import img18 from "@/assets/markets/18.png";
import img19 from "@/assets/markets/19.png";
import img2 from "@/assets/markets/2.png";
import img20 from "@/assets/markets/20.png";
import img21 from "@/assets/markets/21.png";
import img22 from "@/assets/markets/22.png";
import img23 from "@/assets/markets/23.png";
import img24 from "@/assets/markets/24.png";
import img25 from "@/assets/markets/25.png";
import img26 from "@/assets/markets/26.png";
import img27 from "@/assets/markets/27.png";
import img28 from "@/assets/markets/28.png";
import img29 from "@/assets/markets/29.png";
import img3 from "@/assets/markets/3.png";
import img4 from "@/assets/markets/4.png";
import img5 from "@/assets/markets/5.png";
import img6 from "@/assets/markets/6.png";
import img7 from "@/assets/markets/7.png";
import img8 from "@/assets/markets/8.png";
import img9 from "@/assets/markets/9.png";

import { v4 as uuidv4 } from "uuid";

export const marketsDataArr = [
  {
    id: uuidv4(),
    img: img1,
    title: "BTC",
    subTitle: "Bitcoin",
    price: "70,110.45",
    changeRate: "1.27",
    changeStatus: true,
    volume: "27.41B",
    marketCap: "1371.81B",
  },
  {
    id: uuidv4(),
    img: img2,
    title: "ETH",
    subTitle: "Ethereum",
    price: "3,110.45",
    changeRate: "0.67",
    changeStatus: true,
    volume: "12.22B",
    marketCap: "454.21B",
  },
  {
    id: uuidv4(),
    img: img3,
    title: "BNB",
    subTitle: "BNB",
    price: "232.1",
    changeRate: "7.12",
    changeStatus: true,
    volume: "13.53B",
    marketCap: "71.11B",
  },
  {
    id: uuidv4(),
    img: img4,
    title: "SOL",
    subTitle: "Solana",
    price: "54,345",
    changeRate: "42.1",
    changeStatus: true,
    volume: "90.1B",
    marketCap: "23.1B",
  },
  {
    id: uuidv4(),
    img: img5,
    title: "USDC",
    subTitle: "USD Coin",
    price: "110.32",
    changeRate: "8.27",
    changeStatus: false,
    volume: "41B",
    marketCap: "81.11B",
  },
  {
    id: uuidv4(),
    img: img6,
    title: "XRP",
    subTitle: "Ripple",
    price: "1243.45",
    changeRate: "3.11",
    changeStatus: false,
    volume: "4.11B",
    marketCap: "711.31B",
  },
  {
    id: uuidv4(),
    img: img7,
    title: "DOGE",
    subTitle: "Dogecoin",
    price: "53.21",
    changeRate: "2.18",
    changeStatus: true,
    volume: "9.1B",
    marketCap: "834.1B",
  },
  {
    id: uuidv4(),
    img: img8,
    title: "ADA",
    subTitle: "Cardano",
    price: "0.45",
    changeRate: "3.31",
    changeStatus: false,
    volume: "27.41B",
    marketCap: "65.1B",
  },
  {
    id: uuidv4(),
    img: img9,
    title: "SHIB",
    subTitle: "SHIBA INU",
    price: "70,110.45",
    changeRate: "1.27",
    changeStatus: true,
    volume: "27.41B",
    marketCap: "1371.81B",
  },
  {
    id: uuidv4(),
    img: img10,
    title: "AVAX",
    subTitle: "Avalanche",
    price: "00112.43",
    changeRate: "2.7",
    changeStatus: true,
    volume: "0027.41B",
    marketCap: "98.11B",
  },
  {
    id: uuidv4(),
    img: img11,
    title: "WBTC",
    subTitle: "Wrapped Bitcoin",
    price: "110.12",
    changeRate: "7.37",
    changeStatus: false,
    volume: "8.33B",
    marketCap: "00043.54B",
  },
  {
    id: uuidv4(),
    img: img12,
    title: "LINK",
    subTitle: "ChainLink",
    price: "17.79",
    changeRate: "0.27",
    changeStatus: true,
    volume: "1.41B",
    marketCap: "32.0B",
  },
  {
    id: uuidv4(),
    img: img13,
    title: "DOT",
    subTitle: "Polkadot",
    price: "10,88.13",
    changeRate: "7.34",
    changeStatus: true,
    volume: "12.41B",
    marketCap: "00.123B",
  },
  {
    id: uuidv4(),
    img: img14,
    title: "TRX",
    subTitle: "Tron",
    price: "9.45",
    changeRate: "0.14",
    changeStatus: false,
    volume: "7.4B",
    marketCap: "90.081B",
  },
  {
    id: uuidv4(),
    img: img15,
    title: "BCH",
    subTitle: "Bitcoin Cash",
    price: "110.45",
    changeRate: "00.27",
    changeStatus: true,
    volume: "11.56B",
    marketCap: "1371.81B",
  },
  {
    id: uuidv4(),
    img: img16,
    title: "NEAR",
    subTitle: "Near Protocol",
    price: "34.343",
    changeRate: "2.29",
    changeStatus: false,
    volume: "42.2B",
    marketCap: "534.2B",
  },
  {
    id: uuidv4(),
    img: img17,
    title: "MATIC",
    subTitle: "Polygon",
    price: "70,110.45",
    changeRate: "1.27",
    changeStatus: true,
    volume: "27.41B",
    marketCap: "1371.81B",
  },
  {
    id: uuidv4(),
    img: img18,
    title: "UNI",
    subTitle: "Uuiswap",
    price: "99.14",
    changeRate: "4.43",
    changeStatus: false,
    volume: "41.008B",
    marketCap: "00.90B",
  },
  {
    id: uuidv4(),
    img: img19,
    title: "PEPE",
    subTitle: "Pepe",
    price: "110.18",
    changeRate: "3.76",
    changeStatus: true,
    volume: "4.22B",
    marketCap: "002.21B",
  },
  {
    id: uuidv4(),
    img: img20,
    title: "LTC",
    subTitle: "Litecoin",
    price: "82.17",
    changeRate: "003.90",
    changeStatus: true,
    volume: "233.22B",
    marketCap: "145.81B",
  },
  {
    id: uuidv4(),
    img: img21,
    title: "ICP",
    subTitle: "Internet Computer",
    price: "54.43",
    changeRate: "9.3",
    changeStatus: true,
    volume: "4.3B",
    marketCap: "0071.1B",
  },
  {
    id: uuidv4(),
    img: img22,
    title: "DAI",
    subTitle: "Dai",
    price: "00134.99",
    changeRate: "6.4",
    changeStatus: true,
    volume: "31.3B",
    marketCap: "543.77B",
  },
  {
    id: uuidv4(),
    img: img23,
    title: "ETC",
    subTitle: "Ethereum Classic",
    price: "70,110.45",
    changeRate: "1.27",
    changeStatus: true,
    volume: "27.41B",
    marketCap: "1371.81B",
  },
  {
    id: uuidv4(),
    img: img24,
    title: "RNDR",
    subTitle: "Render Token",
    price: "9.17",
    changeRate: "5.29",
    changeStatus: true,
    volume: "5.367B",
    marketCap: "0004.6B",
  },
  {
    id: uuidv4(),
    img: img25,
    title: "APT",
    subTitle: "Aptos",
    price: "70,110.45",
    changeRate: "1.27",
    changeStatus: true,
    volume: "27.41B",
    marketCap: "223.81B",
  },
  {
    id: uuidv4(),
    img: img26,
    title: "HBAR",
    subTitle: "Hedara Hashgraph",
    price: "32.09",
    changeRate: "5.53",
    changeStatus: true,
    volume: "00.13B",
    marketCap: "141.21B",
  },
  {
    id: uuidv4(),
    img: img27,
    title: "WBETH",
    subTitle: "Wrapped Beacon ETH",
    price: "55.05",
    changeRate: "27",
    changeStatus: true,
    volume: "41B",
    marketCap: "81B",
  },
  {
    id: uuidv4(),
    img: img28,
    title: "IMX",
    subTitle: "ImmutableX",
    price: "70,110.45",
    changeRate: "1.27",
    changeStatus: true,
    volume: "27.41B",
    marketCap: "1371.81B",
  },
  {
    id: uuidv4(),
    img: img29,
    title: "WIF",
    subTitle: "Dogwifhat",
    price: "20.25",
    changeRate: "0001.98",
    changeStatus: true,
    volume: "19B",
    marketCap: "89B",
  },
];
