import img1 from "@/assets/markets/1.png";
import img10 from "@/assets/markets/10.png";
import img11 from "@/assets/markets/11.png";
import img12 from "@/assets/markets/12.png";
import img13 from "@/assets/markets/13.png";
import img14 from "@/assets/markets/14.png";
import img15 from "@/assets/markets/15.png";
import img16 from "@/assets/markets/16.png";
import img17 from "@/assets/markets/17.png";
import img18 from "@/assets/markets/18.png";
import img19 from "@/assets/markets/19.png";
import img2 from "@/assets/markets/2.png";
import img20 from "@/assets/markets/20.png";
import img3 from "@/assets/markets/3.png";
import img4 from "@/assets/markets/4.png";
import img5 from "@/assets/markets/5.png";
import img6 from "@/assets/markets/6.png";
import img7 from "@/assets/markets/7.png";
import img8 from "@/assets/markets/8.png";
import img9 from "@/assets/markets/9.png";

import { v4 as uuidv4 } from "uuid";
export const walletDataArr = [
  {
    id: uuidv4(),
    img: img1,
    title: "BTC",
    subTitle: "Bitcoin",
    price: "0.00",
    changeRate: "1.27",
    changeStatus: true,
    volume: "27.41B",
    marketCap: "1371.81B",
  },
  {
    id: uuidv4(),
    img: img2,
    title: "ETH",
    subTitle: "Ethereum",
    price: "0.00",
    changeRate: "0.67",
    changeStatus: true,
    volume: "12.22B",
    marketCap: "454.21B",
  },
  {
    id: uuidv4(),
    img: img3,
    title: "BNB",
    subTitle: "BNB",
    price: "0.00",
    changeRate: "7.12",
    changeStatus: true,
    volume: "13.53B",
    marketCap: "71.11B",
  },
  {
    id: uuidv4(),
    img: img4,
    title: "SOL",
    subTitle: "Solana",
    price: "0.00",
    changeRate: "42.1",
    changeStatus: true,
    volume: "90.1B",
    marketCap: "23.1B",
  },
  {
    id: uuidv4(),
    img: img5,
    title: "USDC",
    subTitle: "USD Coin",
    price: "0.00",
    changeRate: "8.27",
    changeStatus: false,
    volume: "41B",
    marketCap: "81.11B",
  },
  {
    id: uuidv4(),
    img: img6,
    title: "XRP",
    subTitle: "Ripple",
    price: "0.00",
    changeRate: "3.11",
    changeStatus: false,
    volume: "4.11B",
    marketCap: "711.31B",
  },
  {
    id: uuidv4(),
    img: img7,
    title: "DOGE",
    subTitle: "Dogecoin",
    price: "0.00",
    changeRate: "2.18",
    changeStatus: true,
    volume: "9.1B",
    marketCap: "834.1B",
  },
  {
    id: uuidv4(),
    img: img8,
    title: "ADA",
    subTitle: "Cardano",
    price: "0.00",
    changeRate: "3.31",
    changeStatus: false,
    volume: "27.41B",
    marketCap: "65.1B",
  },
  {
    id: uuidv4(),
    img: img9,
    title: "SHIB",
    subTitle: "SHIBA INU",
    price: "0.00",
    changeRate: "1.27",
    changeStatus: true,
    volume: "27.41B",
    marketCap: "1371.81B",
  },
  {
    id: uuidv4(),
    img: img10,
    title: "AVAX",
    subTitle: "Avalanche",
    price: "0.00",
    changeRate: "2.7",
    changeStatus: true,
    volume: "0027.41B",
    marketCap: "98.11B",
  },
  {
    id: uuidv4(),
    img: img11,
    title: "WBTC",
    subTitle: "Wrapped Bitcoin",
    price: "0.00",
    changeRate: "7.37",
    changeStatus: false,
    volume: "8.33B",
    marketCap: "00043.54B",
  },
  {
    id: uuidv4(),
    img: img12,
    title: "LINK",
    subTitle: "ChainLink",
    price: "0.00",
    changeRate: "0.27",
    changeStatus: true,
    volume: "1.41B",
    marketCap: "32.0B",
  },
  {
    id: uuidv4(),
    img: img13,
    title: "DOT",
    subTitle: "Polkadot",
    price: "0.00",
    changeRate: "7.34",
    changeStatus: true,
    volume: "12.41B",
    marketCap: "00.123B",
  },
  {
    id: uuidv4(),
    img: img14,
    title: "TRX",
    subTitle: "Tron",
    price: "0.00",
    changeRate: "0.14",
    changeStatus: false,
    volume: "7.4B",
    marketCap: "90.081B",
  },
  {
    id: uuidv4(),
    img: img15,
    title: "BCH",
    subTitle: "Bitcoin Cash",
    price: "0.00",
    changeRate: "00.27",
    changeStatus: true,
    volume: "11.56B",
    marketCap: "1371.81B",
  },
  {
    id: uuidv4(),
    img: img16,
    title: "NEAR",
    subTitle: "Near Protocol",
    price: "0.00",
    changeRate: "2.29",
    changeStatus: false,
    volume: "42.2B",
    marketCap: "534.2B",
  },
  {
    id: uuidv4(),
    img: img17,
    title: "MATIC",
    subTitle: "Polygon",
    price: "0.00",
    changeRate: "1.27",
    changeStatus: true,
    volume: "27.41B",
    marketCap: "1371.81B",
  },
  {
    id: uuidv4(),
    img: img18,
    title: "UNI",
    subTitle: "Uuiswap",
    price: "0.00",
    changeRate: "4.43",
    changeStatus: false,
    volume: "41.008B",
    marketCap: "00.90B",
  },
  {
    id: uuidv4(),
    img: img19,
    title: "PEPE",
    subTitle: "Pepe",
    price: "0.00",
    changeRate: "3.76",
    changeStatus: true,
    volume: "4.22B",
    marketCap: "002.21B",
  },
  {
    id: uuidv4(),
    img: img20,
    title: "LTC",
    subTitle: "Litecoin",
    price: "0.00",
    changeRate: "003.90",
    changeStatus: true,
    volume: "233.22B",
    marketCap: "145.81B",
  },
];
